### ISSUE TITLE
installation via cpanm fails

### ISSUE THREAD

**Issue by shuntaka** [aki2o/plsense#25]
Hi.  thankyou for creating an awesome software.
When I try installing plsense by passing the latest PlSense-*.tar.gz to cpanm,  I get the following error in the build.log and the installation fails.  (I am using cpanm 1.7022  and perl 5.16.3)
I was wondering if you could tell me any idea for the cause of the issue.

     Failed test 'default config about cache directory'
     at t/92_config.t line 55.
            got: 'cachedir=/var/folders/6b/3jwfxzgx6p17wq01m2b8h2b00000gp/T/.plsense.work/.plsense.d '
       expected: 'cachedir=/var/folders/6b/3jwfxzgx6p17wq01m2b8h2b00000gp/T//.plsense.work/.plsense.d '
    Looks like you failed 1 test of 33.
  t/92_config.t .......... 
  Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/33 subtests

**Comment by aki2o** [comment]
This cause is in test code couldn't consider the end of value of TMP, TMPDIR equals "/".
I created a new release. Could you try it?

**Comment by shuntaka** [comment]
The new release works fine. Thank you very much for the quick response !
