### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by kb01** [aki2o/plsense#30]
I'm getting errors when trying to install Plsense on Windows via cpanminus.

This is the log file: http://pastebin.com/raw/icrMEb8a.

I need some help.
Thanks.

**Comment by aki2o** [comment]
Hi, @kb01 
It seems to not be able to resolve Windows format path.
What perl have you installed? ActivePerl?
You needs a unix shell like Cygwin to use PlSense.

Perhaps I can't help you because I don't have Windows at present...

**Comment by kb01** [comment]
I have Strawberry Perl installed.
Cygwin didn't the job.
I will try using another OS.
